language: node_js
node_js:
  - node
branches:
  only:
    - master
script:
  - npm run build
after_success:
  - find dist -type f -exec curl -T {} -u ${SFTP_USER}:${SFTP_PASSWORD} --ftp-create-dirs ${SFTP_HOST} \;
